Repository arduino/arduino-fwuploader, pull requests merged in 2021-12, with the labels that each got.

#120 Add generic function to verify checksum
  indexes/download/download.go
Labels: type: enhancement, topic: code

#121 [skip-changelog] Revert "pin task version in workflows running on windows"
  .github/workflows/check-go-cross-build-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, os: windows, topic: infrastructure

#122 Use major version ref of `carlosperate/download-file-action`
  .github/workflows/sync-labels.yml
Labels: type: enhancement, topic: infrastructure
