Repository arduino/arduino-fwuploader, pull requests merged in 2021-08, with the labels that each got.

#96 Examples in commands are not correct
  cli/certificates/flash.go
  cli/firmware/flash.go
Labels: topic: documentation

#97 print progress on stdout only if `--format text` is used
  cli/firmware/flash.go
Labels: type: bug

#98 remove newer vidor firmwares since apparently they are not supported
  generator/boards.json
Labels: topic: infrastructure

#99 Sync certificate check workflows with "template"
  .github/workflows/check-certificates.yml
  .github/workflows/check-notarization-certificates.yml
Labels: type: enhancement, topic: infrastructure

#100 Sync "Check General Formatting" workflow with "template"
  .ecrc
  .editorconfig
  .github/workflows/check-general-formatting-task.yml
  .github/workflows/check-general-formatting.yml
  Taskfile.yml
  cli/certificates/certificates.go
  cli/certificates/flash.go
  cli/cli.go
  cli/firmware/firmware.go
  cli/firmware/flash.go
  cli/firmware/list.go
  cli/globals/globals.go
  cli/version/version.go
  docsgen/main.go
  flasher/certificate.go
  flasher/flasher.go
  flasher/nina.go
  flasher/winc.go
  generator/boards.json
  gon.config.hcl
  indexes/download/download.go
  indexes/download/download_test.go
  indexes/firmwareindex/firmwareindex.go
  indexes/firmwareindex/firmwareindex_test.go
  indexes/indexes.go
  indexes/indexes_test.go
  main.go
  programmers/programmer.go
  version/version.go
Labels: type: enhancement, topic: infrastructure

#101 Sync Markdown checks with "template"
  .github/workflows/check-markdown-task.yml
  .github/workflows/link-validation.yml
  .markdown-link-check.json
  .markdownlint.yml
  README.md
  Taskfile.yml
  markdown-link-check-config.json
Labels: type: enhancement, topic: infrastructure

#102 Make taskfile compatible with Go 1.16
  Taskfile.yml
  go.sum
Labels: type: bug, topic: infrastructure

#103 Sync Python checks with "template" assets
  .flake8
  .github/workflows/check-python-task.yml
  .github/workflows/lint-python.yml
  Taskfile.yml
  poetry.lock
  pyproject.toml
Labels: type: enhancement, topic: infrastructure

#107 Add CI workflow to publish tester builds
  .github/workflows/publish-go-tester-task.yml
Labels: type: enhancement, topic: infrastructure

#105 Sync release assets with templates
  .github/workflows/release-go-task.yml
  Taskfile.yml
  gon.config.hcl
Labels: type: bug, type: enhancement, topic: infrastructure

#106 Sync testing assets with templates
  .github/workflows/check-go-cross-build-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
  README.md
  Taskfile.yml
  poetry.lock
  pyproject.toml
  test/conftest.py
  test/pytest.ini
Labels: type: enhancement, topic: infrastructure

#108 Sync website validation assets with template
  .github/workflows/check-mkdocs-task.yml
  .github/workflows/validate-docs.yaml
  Taskfile.yml
Labels: type: enhancement, topic: infrastructure

#109 Sync Prettier formatting assets with templates
  .github/workflows/check-prettier-formatting-task.yml
  .github/workflows/verify-formatting.yml
  .prettierignore
  Taskfile.yml
  generator/boards.json
Labels: type: enhancement, topic: infrastructure

#111 use s3 sync instead of ugly script to upload index to downloads server
  .github/workflows/generate-index.yml
  generator/s3Copy.sh
Labels: topic: infrastructure

#110 Run relevant workflows on release branch creation
  .github/workflows/check-go-cross-build-task.yml
  .github/workflows/publish-go-tester-task.yml
  .github/workflows/test-go-integration-task.yml
  .github/workflows/test-go-task.yml
Labels: type: enhancement, topic: infrastructure

#112 bump mbed core to latest
  .github/workflows/generate-index.yml
Labels: type: bug, topic: infrastructure
