Repository arduino/arduino-fwuploader, pull requests merged in 2021-05, with the labels that each got.

#32 Refactor code structure to be similar to other Tooling Team projects
  README.md
  cli/cli.go
  go.mod
  go.sum
  main.go
  modules/nina/certificates.go
  modules/nina/flasher.go
  modules/nina/nina.go
  modules/sara/flasher.go
  modules/sara/sara.go
  modules/winc/certificates.go
  modules/winc/flasher.go
  modules/winc/winc.go
  programmers/avrdude/avrdude.go
  programmers/bossac/bossac.go
  programmers/rp2040load/rp2040load.go
  utils/context/context.go
  utils/flasher.go
  utils/utils.go
  utils/utils_test.go
Labels: topic: code

#33 [skip changelog] Disabled package index snippet generation
  .github/workflows/release.yml
Labels: topic: infrastructure

#35 Use new arduino/setup-task action name in CI/CD workflows
  .github/workflows/link-validation.yml
  .github/workflows/release.yml
  .github/workflows/test.yaml
  .github/workflows/verify-formatting.yml
Labels: topic: infrastructure, type: enhancement

#36 add `version` subcommand
  cli/cli.go
  cli/version/version.go
  version/version.go
Labels: topic: code, type: enhancement
