Repository arduino/arduino-fwuploader, pull requests merged in 2021-07, with the labels that each got.

#71 Enhance the documentation and rearrange `README.md`
  README.md
  docs/README.md
  docs/index.md
  docs/installation.md
  docs/usage.md
  mkdocs.yml
Labels: topic: documentation

#75 [skip-changelog] fix link validation workflow
  docs/usage.md
Labels: topic: documentation, type: bug

#76 harden the flashing process on win pt2
  cli/firmware/flash.go
Labels: os: windows, type: bug

#77 Replace missing link URL definition for installation docs
  docs/usage.md
Labels: topic: documentation, type: bug

#78 Generate documentation before running link check
  Taskfile.yml
  docs/usage.md
Labels: topic: documentation

#79 fix size in package_index.json
  DistTasks.yml
Labels: topic: infrastructure, type: bug

#80 [skip-changelog] add step in release wf to push on s3 released files
  .github/workflows/release.yml
Labels: topic: infrastructure, type: enhancement

#81 [skip-changelog] change docs link: point to latest version
  README.md
Labels: topic: documentation

#83 update rp2040connect precompiled sketch to mbed_nano@2.3.0
  firmwares/NINA/FirmwareUpdater.nanorp2040connect.ino.elf
Labels: type: enhancement

#82 Generate automatically `module_firmware_index.json`
  .github/workflows/generate-index.yml
  .gitignore
  Taskfile.yml
  generator/generator.py
  generator/s3Copy.sh
Labels: topic: infrastructure, type: enhancement

#84 refactor how the generator for the `module_firmware_index.json` works
  firmwares/NINA/1.0.0/NINA.bin
  firmwares/NINA/1.1.0/NINA.bin
  firmwares/NINA/1.2.1/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.2.1/NINA.bin
  firmwares/NINA/1.2.2/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.2.2/NINA.bin
  firmwares/NINA/1.2.3/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.2.3/NINA.bin
  firmwares/NINA/1.2.4/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.2.4/NINA.bin
  firmwares/NINA/1.3.0/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.3.0/NINA.bin
  firmwares/NINA/1.4.0/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.0/NINA.bin
  firmwares/NINA/1.4.1/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.1/NINA.bin
  firmwares/NINA/1.4.2/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.2/NINA.bin
  firmwares/NINA/1.4.3/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.3/NINA.bin
  firmwares/NINA/1.4.4/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.4/NINA.bin
  firmwares/NINA/1.4.5/NINA-arduino.mbed_nano.nanorp2040connect.bin
  firmwares/NINA/1.4.5/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.5/NINA.bin
  firmwares/NINA/1.4.6/NINA-arduino.mbed_nano.nanorp2040connect.bin
  firmwares/NINA/1.4.6/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.6/NINA.bin
  firmwares/NINA/1.4.7/NINA-arduino.mbed_nano.nanorp2040connect.bin
  firmwares/NINA/1.4.7/NINA-arduino.megaavr.uno2018.bin
  firmwares/NINA/1.4.7/NINA.bin
  firmwares/NINA/FirmwareUpdater.unowifirev2.without_bl.ino.hex
  firmwares/WINC1500/19.4.4/WINC1500-arduino.samd.mkr1000.bin
  firmwares/WINC1500/19.5.2/WINC1500-arduino.samd.mkr1000.bin
  firmwares/WINC1500/19.5.4/WINC1500-arduino.samd.mkr1000.bin
  firmwares/WINC1500/19.6.1/WINC1500-arduino.samd.mkr1000.bin
  firmwares/loader/arduino.mbed_nano.nanorp2040connect/loader.elf
  firmwares/loader/arduino.megaavr.uno2018/loader.hex
  firmwares/loader/arduino.samd.mkr1000/loader.bin
  firmwares/loader/arduino.samd.mkrvidor4000/loader.bin
  firmwares/loader/arduino.samd.mkrwifi1010/loader.bin
  firmwares/loader/arduino.samd.nano_33_iot/loader.bin
  generator/boards.json
  generator/generator.py
  generator/raw_boards.json
Labels: type: enhancement

#86 [skip-changelog] fix wrong workflow trigger
  .github/workflows/generate-index.yml
Labels: type: bug

#87 harden cert flash on windows pt3 (was using port before touch)
  cli/certificates/flash.go
Labels: type: bug

#88 change archive type from bz2 to gz
  .github/workflows/release.yml
  DistTasks.yml
  extras/package_index.json.template
Labels: type: enhancement

#89 [skip-changelog] save the `private.key` in `/tmp`
  .github/workflows/generate-index.yml
Labels: priority: high, topic: security

#90 Change public gpg key
  indexes/download/gpg_keys/module_firmware_index_public.gpg.key
  indexes/download/rice-box.go
Labels: topic: security

#94 update README.md
  README.md
Labels: topic: documentation
