Repository arduino/arduino-fwuploader, pull requests merged in 2021-06, with the labels that each got.

#44 [skip changelog] Add logging support
  cli/cli.go
  go.mod
  go.sum
Labels: topic: code, type: enhancement

#47 Add module name to firmware object in index json
  generator/generator.py
Labels: type: enhancement

#49 add functions to download and load indexes, tools and sketches
  cli/cli.go
  cli/globals/globals.go
  go.mod
  go.sum
  indexes/download/download.go
  indexes/download/download_test.go
  indexes/download/gpg_keys/module_firmware_index_public.gpg.key
  indexes/download/rice-box.go
  indexes/download/testdata/module_firmware_index.json
  indexes/download/testdata/module_firmware_index.json.sig
  indexes/download/testdata/package_index.json
  indexes/download/testdata/package_index.json.sig
  indexes/firmwareindex/firmwareindex.go
  indexes/firmwareindex/firmwareindex_test.go
  indexes/firmwareindex/testdata/module_firmware_index.json
  indexes/firmwareindex/testdata/module_firmware_index.json.sig
  indexes/indexes.go
  indexes/indexes_test.go
  indexes/testdata/package_index.json
  indexes/testdata/package_index.json.sig
Labels: topic: code

#54 Add `certificates flash` command
  cli/certificates/certificates.go
  cli/certificates/flash.go
  cli/cli.go
Labels: topic: code, type: enhancement

#55 cleanup code-base after refactoring
  cli/cli.go
  go.mod
  modules/nina/certificates.go
  modules/nina/flasher.go
  modules/nina/nina.go
  modules/sara/flasher.go
  modules/sara/sara.go
  modules/winc/certificates.go
  modules/winc/flasher.go
  modules/winc/winc.go
  programmers/avrdude/avrdude.go
  programmers/bossac/bossac.go
  programmers/rp2040load/rp2040load.go
  utils/context/context.go
  utils/flasher.go
  utils/utils.go
  utils/utils_test.go
Labels: topic: code, type: enhancement

#57 fix 🐛 causing panic with mkr1000
  cli/certificates/flash.go
  cli/firmware/flash.go
Labels: type: bug

#58 harden the flashing process
  cli/certificates/flash.go
  cli/firmware/flash.go
Labels: topic: code, type: enhancement

#61 add back `--retries` flag
  cli/firmware/flash.go
Labels: topic: code, type: enhancement

#62 rename FirmwareUploader to arduino-firmwareuploader
  .github/workflows/check-certificates.yml
  .github/workflows/check-notarization-certificates.yml
  .github/workflows/link-validation.yml
  .github/workflows/release.yml
  .gitignore
  README.md
  Taskfile.yml
  cli/certificates/certificates.go
  cli/certificates/flash.go
  cli/cli.go
  cli/firmware/firmware.go
  cli/firmware/flash.go
  cli/firmware/list.go
  cli/globals/globals.go
  cli/version/version.go
  flasher/certificate.go
  flasher/flasher.go
  flasher/nina.go
  flasher/sara.go
  flasher/winc.go
  generator/generator.py
  go.mod
  gon.config.hcl
  indexes/download/download.go
  indexes/download/download_test.go
  indexes/firmwareindex/firmwareindex.go
  indexes/firmwareindex/firmwareindex_test.go
  indexes/indexes.go
  indexes/indexes_test.go
  main.go
  mkdocs.yml
  programmers/programmer.go
  pyproject.toml
  test/conftest.py
  test/test_main.py
  version/version.go
Labels: topic: documentation, topic: infrastructure

#63 remove firmwares dir from released archives (not useful anymore)
  DistTasks.yml
Labels: type: enhancement

#64 Add CI workflow to deploy a versioned MkDocs-based website to GitHub Pages
  .github/workflows/publish-docs.yaml
  .github/workflows/validate-docs.yaml
  .gitignore
  Taskfile.yml
  docs/build/build.py
  docs/commands/.gitkeep
  docsgen/main.go
  go.sum
  mkdocs.yml
  poetry.lock
  pyproject.toml
Labels: topic: documentation

#65 Remove support for SARA module
  README.md
  cli/certificates/flash.go
  cli/firmware/flash.go
  firmwares/SARA/5.6A2_01/5.6A2.00-to-5.6A2.01.pkg
  firmwares/SARA/5.6A2_01/5.6A2_01_to_99.pkg
  firmwares/SARA/5.6A2_01/99_to_5.6A2_01.pkg
  firmwares/SARA/SerialSARAPassthrough.ino.bin
  flasher/sara.go
  generator/generator.py
  generator/raw_boards.json
  indexes/download/testdata/module_firmware_index.json
  indexes/download/testdata/module_firmware_index.json.sig
  indexes/firmwareindex/firmwareindex.go
  indexes/firmwareindex/testdata/module_firmware_index.json
  indexes/firmwareindex/testdata/module_firmware_index.json.sig
Labels: topic: code

#66 fix `version` command not working correctly in the released binary
  DistTasks.yml
Labels: type: bug

#70 add progress during firmware flashing
  cli/firmware/flash.go
  flasher/flasher.go
  flasher/nina.go
  flasher/winc.go
Labels: type: enhancement
