Repository arduino/arduino-fwuploader, pull requests merged in 2023-07, with the labels that each got.

#172 Generate `plugin_firmware_index.json` with new boards data
  .github/workflows/generate-index.yml
  firmwares/ESP32-S3/0.1.0/ESP32-S3.bin
  firmwares/ESP32-S3/0.2.0/ESP32-S3.bin
  generator/generator.py
  generator/new_boards.json
Labels: type: enhancement, topic: code

#176 Rename plugin
  generator/generator.py
Labels: type: enhancement, topic: infrastructure

#173 Introducing plugins system
  .licensed.yml
  .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/cores/packagemanager.dep.yml
  .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/discovery.dep.yml
  .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/discovery/discoverymanager.dep.yml
  .licenses/arduino-fwuploader/go/github.com/arduino/arduino-cli/arduino/sketch.dep.yml
  .licenses/arduino-fwuploader/go/github.com/arduino/go-timeutils.dep.yml
  .licenses/arduino-fwuploader/go/golang.org/x/exp/constraints.dep.yml
  .licenses/arduino-fwuploader/go/golang.org/x/exp/slices.dep.yml
  .licenses/arduino-fwuploader/go/gopkg.in/yaml.v3.dep.yml
  certificates/certutils.go
  cli/certificates/flash.go
  cli/cli.go
  cli/common/common.go
  cli/firmware/flash.go
  cli/firmware/getversion.go
  cli/firmware/list.go
  cli/globals/globals.go
  flasher/nina.go
  flasher/winc.go
  go.mod
  go.sum
  indexes/download/download.go
  indexes/firmwareindex/firmwareindex.go
  indexes/firmwareindex/firmwareindex_test.go
  indexes/indexes.go
  indexes/indexes_test.go
  plugin/plugin.go
Labels: type: enhancement, topic: code

#177 Fix regression on winc when flashing pem certificates
  flasher/winc.go
Labels: topic: code, type: imperfection

#178 Add documentation on the new plugin system
  docs/index.md
  docs/plugins.md
Labels: type: enhancement, topic: documentation

#179 Add documentation on the new plugin system
  docs/index.md
  docs/plugins.md
Labels: type: enhancement, topic: documentation

#187 Add "Plugins" page to the website navigation panel
  mkdocs.yml
Labels: topic: infrastructure, topic: documentation, type: imperfection

#207 Fix the name not being present on the index
  generator/generator.py
  generator/new_boards.json
Labels: topic: infrastructure
