Repository arduino/arduino-fwuploader, pull requests merged in 2023-08, with the labels that each got.

#212 Fix Improper Certificate Validation
  certificates/certutils.go
Labels: type: enhancement, topic: security

#206 Add portenta C33 firmware to the plugin system
  firmwares/ESP32-C3/1.5.0/ESP32-C3.bin
  generator/new_boards.json
Labels: status: on hold, topic: infrastructure

#213 Update plugin doc
  docs/plugins.md
Labels: type: enhancement, topic: documentation

#214 Throw an error when a tool has no compatible flavour with the current OS
  indexes/download/download.go
  indexes/download/download_test.go
Labels: topic: code, type: imperfection

#215 Print error message on certificate flash failure
  cli/certificates/flash.go
Labels: topic: code, type: imperfection

#216 Fix wrong scrape of Root Certificates
  certificates/certutils.go
  certificates/certutils_test.go
  cli/certificates/flash.go
  docs/plugins.md
Labels: topic: code, type: imperfection
